### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by JaviiGil**

### CODE REVIEW

**Comment by rgcmme** [comment]
- There are conflicts in the Assignment 1 file. Reset this file to remove the conflicts.

**Comment by rgcmme** [comment]
@dgarijo once the conflict is solved and assignment 4 is correct you can merge the pull request.

**Comment by dgarijo** [comment]
ok, @JaviiGil let me know when the conflict is solved and I will have a look

**Comment by dgarijo** [comment]
Also, @JaviiGil you are uploading notebooks for assignment 4, which we said multiple time we would not accept as part of a pull request. You need to upload python scripts

**Pull request merged**
